### ISSUE TITLE
Define output path

### ISSUE THREAD

**Issue by DigiLive** [mnlipp/EclipseMinifyBuilder#7]
Is there a way to define the output path of the minified file?
E.g. 
Input: `./src/js/file.js`
Output: `./dist/file.min.js`

**Comment by mnlipp** [comment]
No. And it wouldn't really be a good idea. The assumption is that a user of this plugin doesn't create the minified version as part of some reproducible  build process (e.g. using gradle). Rather, the minified version is assumed to be source code (and must be mainteined in the SCR). That's why it should remain in a source directory.

**Comment by DigiLive** [comment]
It might not be a good idea to you for your use cases, but for others it might be desired because they have other use cases.

Would it hurt to add the option anyway for people who do want to define to output path?
You can always default to the same path as the un-minified file.
